### ISSUE TITLE
Could someone show a piece of samples about "all_comments.txt " file ,I Can't reach the YouTube 

### ISSUE THREAD

**Issue by smartLp** [HackerPoet/YouTubeCommenter#5]
I want to know the format of  all_comments.txt file ,but I can't reach Youtube case the networks .

**Comment by HackerPoet** [comment]
It is a CSV format that uses '~' as the delimiter.  Each row has 3 values:
- YT's video id
- Title of Video
- Comment

You need to create a developer account and project to access the YouTube API.  This should help you get started: https://developers.google.com/youtube/v3/

Once you have your API key, you'll have to add it to Scrape.py at the top of the file.

**Comment by smartLp** [comment]
Thanks
